# NOTE: These settings can be overridden by environment variables as well, in
# particular:
#
#    PGHOST
#    PGPORT
#    PGUSER
#    PGPASS
#    PGDATABASE

Default: &defaults
  user: garry
  password: A6CkoS0DIxF_yX8Xx2hWt91XCOyTSmvEbRp 
  host: localhost
  port: 5432
  database: correspondence
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: correspondence_test
  <<: *defaults

Staging:
  database: correspondence_staging
  poolsize: 100
  <<: *defaults

Production:
  database: correspondence_production
  poolsize: 100
  <<: *defaults
